INSERT INTO role (type) VALUES ('ADMIN')
    ON CONFLICT (type) DO NOTHING;

INSERT INTO role (type) VALUES ('USER')
    ON CONFLICT (type) DO NOTHING;

INSERT INTO role (type) VALUES ('MANAGER')
    ON CONFLICT (type) DO NOTHING;
